# Generated by Django 4.1.2 on 2022-11-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='chatapp',
        ),
    ]
