# Generated by Django 4.1.2 on 2022-11-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_group_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
    ]
